### ISSUE TITLE
[Question] How does one use this in a browser?

### ISSUE THREAD

**Issue by ghost** [mattdesl/gl-sprite-batch#2]
This looks like a really nice library. However, I am a bit confused as to how this is supposed to be used in a browser. I mean, it's an NPM package.

How does one use or compile this for a browser?

**Comment by mattdesl** [comment]
Typically with Browserify, but other build tools like Webpack/JSPM should also work. 

You can use [budo](https://github.com/mattdesl/budo) to quickly launch a browserify dev server.

``` sh
# install the dev server
npm install budo -g

# run it, open the browser, and enable LiveReload
budo src/index.js --open --live
```

It should open `localhost:9966/`. Assuming `src/index.js` is a CommonJS file, now when you save the file it will reload the browser. You can then use the `browserify` command-line or API to bundle for production. You can find all sorts of other [stack.gl modules here](http://stack.gl/packages/).

Be warned; this module is fairly old and experimental, and might have some bugs. :smile: My more recent modules tend to include [package.json `"scripts"`](https://github.com/mattdesl/three-glslify-example/blob/3c6473deebc8b8f3fe95001cfd7af75f66f8d3db/package.json#L31-L32) and dev dependencies so you can just clone, install and run.

**Comment by mattdesl** [comment]
More details:
- [module basics](https://github.com/Jam3/jam3-lesson-module-basics)
- [rapid prototyping with budo + browserify](http://mattdesl.svbtle.com/rapid-prototyping)

**Comment by ghost** [comment]
Thanks a bunch for the information! Browserify looks pretty useful. Having everything in one file gets messy way too quickly. Thanks again for the details.

**Comment by farzher** [comment]
this looks awesome but yeah, i can't figure out how to run it lol.
